### ISSUE TITLE
Fix compile errors

### ISSUE THREAD

**Issue by jmaynard** [Hercules-Aethra/aethra#1]
Hercules should compile cleanly, with no errors or warnings, on every platform it reasonably can. Currently it throws large numbers of errors on at least Linux and macOS.

**Comment by Fish-Git** [comment]
> Currently it throws large numbers of errors on at least Linux and macOS.

I of course cannot speak for macOS, but AFAIK for Linux, it builds cleanly when clang is used instead of gcc.

In my experience gcc absolutely _**sucks**_ a far as throwing errors is concerned, requiring the programmer to have to jump through unnecessary hoops in order to silence them.

But that's of course only my own personal opinion. I myself have given up trying to get Hercules to build cleanly with gcc.

**Comment by jmaynard** [comment]
Actually, I'm not far from having it work. There's jsut one set of warnings that are giving me fits; the last commit knocked out most of them.

Since gcc is the default compiler in most Linux distributions, it's what I'll be targeting.

**Comment by wrljet** [comment]
> Since gcc is the default compiler in most Linux distributions, it's what I'll be targeting.

For Linux, yes.  But for the BSDs and macOS, they tend toward Clang.

**Comment by jmaynard** [comment]
And I'm sure that fixing outstanding warnings on macOS will take care of clang.

**Comment by wrljet** [comment]
> And I'm sure that fixing outstanding warnings on macOS will take care of clang.

Well for macOS, yes.  For Linux, I'm not so sure.

**Comment by Fish-Git** [comment]
> ... the last commit knocked out most of them.

I noticed! &nbsp;`:(`

And for the record, I would to provide _indisputable **proof**_ that gcc truly _**SUCKS**_ as a compiler:
___

1. **dasdload2.h:2206:25: warning: array subscript ‘DATABLK[0]’ is partly outside array bounds of ‘unsigned char[276]’ [-Warray-bounds]**

_(WTF?!)_ This is complete _bullshit!_ The statement it is complaining about is:

```C
              blkp->rec = rec;
```

The `rec` field of the `DATABLK` struct is the _**9th(!) freaking byte**_ of the struct! So why the _F**K_ is it throwing a freaking `array-bounds` warning?! &nbsp; _(**especially** when it already knows the space allocated to `blkp` is **276** freaking bytes!)_

___

2. **tfprint.c:1732:26: warning: '0' flag ignored with precision and ‘%X’ gnu_printf format [-Wformat=]**

This one _(and the next one below)_ illustrates _perfectly_ why I hate gcc. _WTF_ is the purpose of this warning?! To let me know it's going to go ahead and do what I wanted it to do anyway?! What an incredibly _**USELESS**_ warning! What's next?

```C
#define FOO "foo"
#define BAR "bar"
printf(FOO BAR "\n");
```
_"**Warning!** You could have just written "foobar\n" instead!"_

Sheesh! &nbsp; `>:-(`

___

3. **hinlines.h:341:33: warning: ‘Obtain_Interrupt_Lock’ is static but used in inline function ‘s370_per1_gra’ which is not static**

Why the _F**K_ is it telling me that it can't inline a function?! &nbsp;_WHO THE **F\*\*K** cares?!_ &nbsp; I declared the function `inline`! Not _forced_-inline! (i.e. always-line)

The `inline` modifier requests that the function be inlined -- _IF POSSIBLE!_ &nbsp;It's _not_ a demand! It's a request! It means if you can safely inline it, fine! Do so! But if you can't, then that's fine too! Do whatever the fuck you're able or legally can do! If you can't do it, then simply _DON'T DO IT! And keep your stinking pie hole SHUT about it if you can't for jeebus sake!)_ &nbsp;_(Sheesh!)_

___

gcc has a long history of issuing incredibly stupid and unhelpful warnings about shit it has no business _(or valid reason)_ to be warning the user about.

I hate it with a passion. &nbsp; `>8-(`
&nbsp;

**Comment by jmaynard** [comment]
1: **dasdload2.h:2206:25: warning: array subscript ‘DATABLK[0]’ is partly outside array bounds of ‘unsigned char[276]’ [-Warray-bounds]**

This is actually a legitimate complaint. What it's complaining about is that a `DATABLK` won't fit into a 276-byte array - and it's right, because `DATABLK` is declared as a 32k array plus a few values at the beginning. In short, we're lying to the compiler. The right answer is to declare the data area as a flexible length array, something introduced in C99; if the decision is to go to C99 as the baseline, this will be the first thing to get fixed.

2: **tfprint.c:1732:26: warning: '0' flag ignored with precision and ‘%X’ gnu_printf format [-Wformat=]**

This one serves to tell you that you wrote something that might not do what you are expecting. The purpose is to get you to think about it and make sure you're telling the compiler to do what you really want.

3: **hinlines.h:341:33: warning: ‘Obtain_Interrupt_Lock’ is static but used in inline function ‘s370_per1_gra’ which is not static**

This one isn't telling you you can't `inline` a function. (That was my assumption at first, but a bit of digging showed that wasn't the case.) What it's telling you is that you are using a function defined as `static` in an `inline` function that isn't `static`. In C, declaring a function `static` restricts its visibility to the source file it's contained in. If you use it in an `inline`d function elsewhere, then you're requiring it to be visible in other source files, effectively. The answer is not to un-`inline` it; it's to un-`static` it. (The reason I haven't fixed this one yet is because when I remove the `static` declaration, it produces link complaints about not finding one function...so far, haven't figured out why.)

For all that gcc can be annoying, it _**is**_ the standard C compiler for Linux, and as such Aethra **_will_** compile without errors or warnings with it. Any compiler warning is an invitation to consider your code carefully and make sure that it is doing what you intend. That is the goal here.

**Comment by Fish-Git** [comment]
> 1: **dasdload2.h:2206:25: warning: array subscript ‘DATABLK[0]’ is partly outside array bounds of ‘unsigned char[276]’ [-Warray-bounds]**
> 
> This is actually a legitimate complaint.

I beg to differ.



> What it's complaining about is that a `DATABLK` won't fit into a 276-byte array

So? Are we actually _ACCESSING_ anything beyond those 256 bytes that we allocated? No. So no warning is deserved here.

If we tried accessing anything beyond those 256 bytes, _THEN_ a warning would definitely be deserved, but until then, there is no problem so no warning is deserved.

Clang doesn't complain. MSVC doesn't complain. Only gcc complains. _WAY_ too f**king much. You're grasping at straws to legitimize a warning that simply should _not_ be issued.




> 2: **tfprint.c:1732:26: warning: '0' flag ignored with precision and ‘%X’ gnu_printf format [-Wformat=]**
> 
> This one serves to tell you that you wrote something that might not do what you are expecting.

But it's doing _EXACTLY_ what I was expecting.

> The purpose is to get you to think about it and make sure you're telling the compiler to do what you really want.

But it _IS_ doing what I really want!

It's purpose is to annoy the programmer with unhelpful and meaningless diagnostics for "potential problems" which are not potential problems at all. Again, you're grasping at straws.



> 3: **hinlines.h:341:33: warning: ‘Obtain_Interrupt_Lock’ is static but used in inline function ‘s370_per1_gra’ which is not static**
> 
> This one isn't telling you you can't `inline` a function. (That was my assumption at first, but a bit of digging showed that wasn't the case.) What it's telling you is that you are using a function defined as `static` in an `inline` function that isn't `static`.

You mean "in a function that isn't static." The fact that it's declared inline has nothing to do with it. Yes? That's what you're saying?

> In C, declaring a function `static` restricts its visibility to the source file it's contained in.

Duh!

> If you use it in an `inline`d function elsewhere, then you're requiring it to be visible in other source files, effectively.

And it is.

In _every_ source file where the `PER_GRA_CHECK` macro is used, `hercules.h` is #included ahead of `opcode.h`, and `hercules.h` automatically #includes `hercules.h`. So _everywhere_ that `s370_per1_gra` is being used, the static `Obtain_Interrupt_Lock` and `Release_Interrupt_Lock` lock static functions are visible.

So what's the problem?

Answer: _there is no problem._

That's why clang doesn't complain, and neither does MSVC.

So then why is the diagnostic being issued?

Answer: because gcc is stupid.

**Comment by jmaynard** [comment]
> If we tried accessing anything beyond those 256 bytes, THEN a warning would definitely be deserved, but until then, there is no problem so no warning is deserved.

According to friends who are a lot more conversant with the C standard than I am, the moment you try to dereference any pointer to a `DATABLK` in an area of memory too small to contain its declared size, you're in undefined behavior territory.

> But it IS doing what I really want. It even said so.

How is it supposed to know that? And, for that matter, that flag was only specified on a few lines of the many, many fixed-width `%X` fields mentioned in that file. That change just makes them consistent with each other, and makes gcc happy. Win win.

> You mean "in a function that isn't static." The fact that it's declared inline has nothing to do with it. Yes? That's what you're saying?

I **think** so, but the warning message **does** mention that it's in an `inline` function. I'm not certain of the exact effect. Regardless, the issue isn't `inline`, it's `static`.

> That's why clang doesn't complain, and neither does MSVC.

I can't speak to MSVC, but I'll absolutely guarantee you that clang has its own pedantry to deal with. I spent a decade working on one massive program for macOS and its native compiler (which is an Apple-customized version of clang), and there were plenty of cases where gcc was perfectly happy with code that clang complained to the skies about.

**Comment by Fish-Git** [comment]
> > If we tried accessing anything beyond those 256 bytes, THEN a warning would definitely be deserved, but until then, there is no problem so no warning is deserved.
> 
> According to friends who are a lot more conversant with the C standard than I am, the moment you try to dereference any pointer to a `DATABLK` in an area of memory too small to contain its declared size, you're in undefined behavior territory.

I disagree. The behavior is most certainly _not_ "undefined". To the contrary, the behavior is very well defined -- as long you don't access any of the struct's that would cause unallocated memory to be accessed.

Besides which, would you agree that any "undefined behavior" should be reported with a diagnostic? Yes? That seems to be your argument. Because gcc feels undefined behavior would/could occur, it therefore issues a diagnostic. Yes? Well then why do no other compilers issue any diagnostic under the exact same conditions? Are they all wrong and only gcc is right? That would seem to be your argument.

___
> > But it IS doing what I really want. It even said so.
> 
> How is it supposed to know that?

How can it know _anything_ that I code is what I really want? Answer me that, Mr. Smarty Pants. &nbsp; `:)`

> And, for that matter, that flag was only specified on a few lines of the many, many fixed-width `%X` fields mentioned in that file. That change just makes them consistent with each other, and makes gcc happy. Win win.

You're missing the point. Whether I code it with or without the '0', the results are _always_ going to be exactly the same because the '0' _**will be ignored**_. &nbsp; _Always._

So there is absolutely _no valid reason_ to be issuing this diagnostic.

In fact, I would argue that issuing a diagnostic in such a situation is actually a BUG, as doing so violates documented behavior:
&nbsp;

* https://pubs.opengroup.org/onlinepubs/009604499/functions/fprintf.html

> _For d, i, o, u, x, X, a, A, e, E, f, F, g, and G conversion specifiers, leading zeros (following any indication of sign or base) are used to pad to the field width; no space padding is performed. If the '0' and '-' flags both appear, **the '0' flag is ignored.** For d, i, o, u, x, and X conversion specifiers, if a precision is specified, **the '0' flag is ignored.** If the '0' and '" flags both appear, the grouping characters are inserted before zero padding. For other conversions, the behavior is undefined._

* https://www.gnu.org/software/libc/manual/html_node/Integer-Conversions.html

> _Pad the field with zeros instead of spaces. The zeros are placed after any indication of sign or base. **This flag is ignored** if the ‘-’ flag is also specified, **or if a precision is specified.**_

* https://www.ibm.com/docs/en/i/7.3?topic=functions-printf-print-formatted-characters

> _When used with the d, i, D(n,p) o, u, x, X, a, A, e, E, f, F, g, or G formats, the 0 flag causes leading 0s to pad the output to the field width. The 0 flag is **ignored if precision is specified for an integer** or if the - flag is specified._

* https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170

> _If width is prefixed by 0, leading zeros are added until the minimum width is reached. If both 0 and - appear, **the 0 is ignored**. If 0 is specified for an integer format (i, u, x, X, o, d) and a precision specification is also present -- for example, %04.d -- **the 0 is ignored**. If 0 is specified for the a or A floating-point format, leading zeros are prepended to the mantissa, after the 0x or 0X prefix._

* https://docs.oracle.com/cd/E19253-01/817-6223/chp-fmt-1.2/index.html

> _For d, i, o, u, x, X, e, E, f, g, and G conversions, leading zeroes (following any indication of sign or base) are used to pad to the field width. No space padding is performed. If the 0 and - flags both appear, **the 0 flag is ignored.** For d, i, o, u, x, and X conversions, if a precision is specified, **the 0 flag is ignored.** If the 0 and ' flags both appear, the grouping characters are inserted before the zero padding._

&nbsp;
The key word here is _**"ignored"**_.

Issuing a diagnostic when an unneeded '0' is used is _not_ "ignoring" it.

Issuing a diagnostic in this situation is _uncalled for_. &nbsp; It is a _nuisance_. &nbsp; It is _annoying_.

And it is simply _plain **WRONG**_. &nbsp; _Period_.

___
> > You mean "in a function that isn't static." The fact that it's declared inline has nothing to do with it. Yes? That's what you're saying?
> 
> I **think** so, but the warning message **does** mention that it's in an `inline` function. I'm not certain of the exact effect. Regardless, the issue isn't `inline`, it's `static`.

Then why is the diagnostic being issued? As I've already explained, the static function in question _IS_ visible to the compiler, and "inline" _IS_ only a request, with no reporting _(and certainly no diagnostic!) is necessary should the compiler not inline it (either because it doesn't want to or because it is unable to given the current situation). So why is the diagnostic being issued? Where's the problem? Answer: there is no problem and the diagnostic is being issued because gcc is stupid.

> > That's why clang doesn't complain, and neither does MSVC.
> 
> I can't speak to MSVC, but I'll absolutely guarantee you that clang has its own pedantry to deal with. I spent a decade working on one massive program for macOS and its native compiler (which is an Apple-customized version of clang), and there were plenty of cases where gcc was perfectly happy with code that clang complained to the skies about.

No argument. I agree that all compilers have their own pedantry. But you're avoiding the issue. Why does gcc feel this specific case/situation merits a diagnostic? Why is gcc being pedantic in this specific case? None of the other compilers are. Yes, they're certainly pedantic in other situations I'm sure. But they're not in this situation. So why is gcc? There's no reason for it to be in this specific situation.

Any that's been my point all along: gcc seems to have a bad habit of being pedantic _(or just plain wrong)_ in far too many situations under conditions where most other compilers aren't. **Why is that I wonder? &nbsp;Hmmmm....** &nbsp;_(me: pretends to scratch head trying to figure out the answer)_ &nbsp; `;-)`

**Comment by jmaynard** [comment]
> I disagree. The behavior is most certainly not "undefined". To the contrary, the behavior is very well defined -- as long you don't access any of the struct's fields that would cause unallocated memory to be accessed.

I was incorrect. It's not dereferencing a pointer like that; it's merely having a pointer like that. The C standard clearly says it's undefined behavior. And yes, I would say that a compiler absolutely should throw a warning for undefined behavior that it can detect.

>Well then why do no other compilers issue any diagnostic under the exact same conditions?

Think for a moment about how gcc knew this was a problem: it knew that the argument to malloc() was exactly 267 bytes. That means that it had to know that the value was tested for having the value of 267 and control did not reach that point unless it was. That's pretty sophisticated data flow analysis, and it's entirely believable that the authors of MSVC or clang don't do that to that degree. Not knowing the internals of compilers (hey, I'm a mainframe sysprog, not a compiler geek), I can't begin to tell you why gcc does that or why other compilers don't or what other use gcc makes of that information. But it is entirely undefined behavior, and I have no issue with gcc complaining about it.

------

> How can it know anything that I code is what I really want? Answer me that, Mr. Smarty Pants.   :)

It can't, but what it can do is say "hey, did you expect this 0 to mean something, because it doesn't." That's what it said. We've now spent more time arguing about the warning than it took to fix it.

------

I'm still digging into the exact cause of the `static inline` complaint.

**Comment by jmaynard** [comment]
Fixed the `static inline` issue by making the `per_gra()` functions static as well. Without that, the code actually creates multiple different copies of the same function, one for every time `inlines.h` is `#include`d. No, I don't know why gcc didn't complain about it everywhere, nor why the other compilers don't complain about it, but it's still the wrong thing to do. It's worth a look to see what else is `inline`d like that and defined in a header file and therefore should be declared `static` as well.

**Comment by wrljet** [comment]
Jay,

Did you build with these changes on Clang and MSVC?

Bill

**Comment by jmaynard** [comment]
clang is next. I have built with all but the last change there. I need to set up a Windows VM to build with MSVC on.

**Comment by Fish-Git** [comment]
> > I disagree. The behavior is most certainly not "undefined". To the contrary, the behavior is very well defined -- as long you don't access any of the struct's fields that would cause unallocated memory to be accessed.
> 
> I was incorrect. It's not dereferencing a pointer like that; it's merely having a pointer like that. The C standard clearly says it's undefined behavior.

Oh? Where? Can you point to it? I'd like to read it for myself. I looked for it in the copy I have and couldn't find it anywhere. Maybe I just missed it or didn't look hard enough?

> And yes, I would say that a compiler absolutely should throw a warning for undefined behavior that it can detect.

I agree wholeheartedly.

But I'm still not convinced that what gcc discovered is undefined behavior. As I said, I tried looking in the copies of the 'C' standard that I have _("C Programming Language (C11, DRAFT, N1570, 2011)" and "C Programming Language (C99, FINAL, TC3, 2007)")_ and could not find it anywhere.

Can you help me out and point to where in the C standard it clearly states that this behavior is undefined?

Thanks.

_(Is this perhaps a new thing? Am I looking in the wrong manual?)_

**Comment by jmaynard** [comment]
I'm chasing down some warnings on macOS. It seems things like SIZEOF_INTP an SIZEOF_LONG are generated by the autoconf process...but the actual definitions aren't getting included in the header files. Where are those supposed to be actually defined (I'm guessing config.h, which isn't being generated at all), and how are the definitions supposed to get there?

**Comment by wrljet** [comment]
Jay,

`config.h` will be generated into the same directory as the `Makefile`.  If you are using the out-of-source style
build from Hercules-Helper, that will be the `build` sub-directory under the Hercules sources.

Bill

**Comment by jmaynard** [comment]
Yup, there it is. Not sure why it's not having the intended effect, but I'll keep digging.

**Comment by Fish-Git** [comment]
> > > I disagree. The behavior is most certainly not "undefined". To the contrary, the behavior is very well defined -- as long you don't access any of the struct's fields that would cause unallocated memory to be accessed.
> > 
> > 
> > I was incorrect. It's not dereferencing a pointer like that; it's merely having a pointer like that. The C standard clearly says it's undefined behavior.
> 
> Oh? Where? Can you point to it? I'd like to read it for myself. I looked for it in the copy I have and couldn't find it anywhere. Maybe I just missed it or didn't look hard enough?


> But I'm still not convinced that what gcc discovered is undefined behavior. As I said, I tried looking in the copies of the 'C' standard that I have _("C Programming Language (C11, DRAFT, N1570, 2011)" and "C Programming Language (C99, FINAL, TC3, 2007)")_ and could not find it anywhere.
> 
> Can you help me out and point to where in the C standard it clearly states that this behavior is undefined?

Hello? Any luck locating the 'C' standard clause to backup your claim yet, Jay? As I said, I looked, and could not find it anywhere. Until such proof is offered to backup your claim, I respectfully call bullshit. &nbsp; `;-)`

**Comment by jmaynard** [comment]
Huh. My language lawyer friends tell em that they've dug through the standard and what was so obvious to them turned out not to be explicitly stated.

Even so, as it happens, Hercules had already implemented the fix for that message elsewhere in the code (see `C99_FLEXIBLE_ARRAYS`), so the right answer was to use that as well.

Aethra now compiles cleanly on Linux with gcc 11 and macOS. Now if I can just get my Windows 10 VM set up to build the package...

**Comment by jmaynard** [comment]
Hercules now builds cleanly on the main platforms and any others I know of. Any further compile warnings will be treated as bugs and fixed, so please feel free to file Github issues for them.
